"""made changes to delete sightings when dive is delete

Revision ID: 5e69cc67b620
Revises: 
Create Date: 2023-07-09 17:19:03.065587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e69cc67b620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sightings_dive_id_fkey', 'sightings', type_='foreignkey')
    op.create_foreign_key(None, 'sightings', 'dives', ['dive_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sightings', type_='foreignkey')
    op.create_foreign_key('sightings_dive_id_fkey', 'sightings', 'dives', ['dive_id'], ['id'])
    # ### end Alembic commands ###
